### ISSUE TITLE
Background image no longer available in PageHero

### ISSUE THREAD

**Issue by matteius** [saleor/react-storefront#250]
### Summary

I was relying on the BackgroundImage in the PagerHero which was on the collection entity, but that has been removed from the component, and removed from the outer scope -- so how is one supposed to get the PageHero background image back without a bunch of work?   Also the new sub categories in the PageHero seem not great and were way better in the menus.  It is disappointing the PRs that are getting merged with no description, because it make the direction of this project and the chosen changed totally unclear.   Seems every week the UI heads in some random new direction.

### Steps to reproduce

Merge main branch into a fork that styles the site and watch for breaking changes and weird directions to head in.

### Your `next.config.js` file

n/a

### Builds logs (or link to your logs)

n/a

### Function logs

n/a

**Comment by matteius** [comment]
Ah part of my problem was that the collection and the category objects are in fact different, so I modified those pages to continue passing in those components as that is where the background image comes from.  I am not sure why though a PR from 19 hours ago with no description abandons supporting the background image for the category/collection.

**Comment by matteius** [comment]
Oh man and the cool load more products thing is gone and it just loads everything from the start now :-/

**Comment by matteius** [comment]
I suppose I can get used to it loading everything but eventually I'll probably have too many listings for that to be super mobile friendly.  Are there plans to add pagination then instead of the load more thing?   Why show the sub categories in the PageHero though (I removed it and put the back the image which is definitely better) when the nav menus already show the subcategories?  Ref deployment:  www.mattscoinage.com

**Comment by matteius** [comment]
Yeah I see that before the changes I was getting around a 30-37 in performance score, now I get around a 10:
![image](https://user-images.githubusercontent.com/479892/172993627-16da6908-6402-4a7f-bc80-5db019148144.png)

**Comment by timuric** [comment]
@matteius the goal of the project is to showcase how Saleor API works and provide guidance for the community. We do not intend this to be a generic theme that provides a UI kit for building online shops. Feel free to use component libraries of your choice.

> Are there plans to add pagination then instead of the load more thing?
Yes

> Yeah I see that before the changes I was getting around a 30-37 in performance score, now I get around a 10:
To increase the score I would advise you to fetch data on the server and use `getStaticProps` to cache pages. This is what we are planning to do as well

**Comment by matteius** [comment]
> the goal of the project is to showcase how Saleor API works and provide guidance for the community.

@timuric It still would be nice to have descriptions in the PRs and some kind of roadmap or plan published so that we can understand the direction of the showcase.  I am definitely not the only person who has forked this repository to make an online store and presumably there will be important fixes, even security items that get patched upstream that we would have originally brought in from the example.  

The problem though is either the showcase example is going to be useful towards a framework to build an online store which feels like the ideal to me where we extend the storefront and that leads to other features and enhancements being contributed back tot he framework that further lets us build a configurable UI store.  That would be the full potential of the project, not just an example of an ever changing UI showcase and then when someone decides to build a store with saleor they get all of the improvements at that point in time, fork it, and then good luck pulling in upstream changes.  This is definitely the easier path forward to developing a prototype, but it feels less ideal, and at what point is the showcase considered done?

> To increase the score I would advise you to fetch data on the server and use getStaticProps to cache pages.

Can you expand upon this idea?   When you say fetch data on the server, are you talking about the `pnpm run start` server that runs the react-storefront?  I have this deployed in a Docker container running this way and I bypassed it to the CDN for images.  What would it mean to fetch data on the server and use getStaticProps? -- is this similar to trying to build static pages by hitting the graph QL API during the build cycle and deploying that (with the caveat that to get product updates and changes the site has to be recompiled) are you suggesting a more dynamic way of fetching data live in order to get a better performance score?  Ideally there are ways to improve performance without taking away the dynamic aspects that make it useful to edit products and see them in real time.

**Comment by timuric** [comment]
@matteius 

We provide several packages for building an online store:

1. Payments hooks and Checkout Page that is customizable. This is something that you might want to use without forking to keep up to date with all features. 
https://github.com/saleor/saleor-checkout

2. SDK for building stores, which you can use as a package and update as Saleor core evolves
https://github.com/saleor/saleor-sdk

3. Saleor storefront as a boilerplate, which is meant as a starting point, is not intended to be used as a theme. We believe each store has different needs and in most cases would work quite different from our example. We have ambitious goals to improve the storefront, there are going to be many changes and commits and we don't think it would be realistic to stay up to date with them.  We do acknowledge that the community also needs themes that would be customizable and upgradable like https://www.reactstorefront.io/ or https://www.vuestorefront.io/ but we don't have that planned any time soon. One thing I can promise is that we would try to better separate presentation and business logic to make at least some parts of the code more portable.


> Can you expand upon this idea?

You can use `getStaticProps` with fallback blocking, which would generate pages on request instead of build time
https://github.com/saleor/react-storefront/blob/1b61fb6373e627eb1383612f0df2e54d75494741/pages/%5Bchannel%5D/%5Blocale%5D/products/%5Bslug%5D.tsx#L38

Set revalidate to X seconds to keep cache fresh
https://github.com/saleor/react-storefront/blob/1b61fb6373e627eb1383612f0df2e54d75494741/pages/%5Bchannel%5D/%5Blocale%5D/products/%5Bslug%5D.tsx#L57

Our product page already is using this approach, the issue with the product listing page is that it is using filters that depend on URL query parameters which unfortunately is not supported by `getStaticProps`. We would be looking for a workaround for that.
