### ISSUE TITLE
Error message in dashboard: "Something went wrong: Unauthenticated"

### ISSUE THREAD

**Issue by gleniat** [saleor/react-storefront#283]
Hi,

I tried to set up the checkout and checkout-app according to the deployment manual in README. However, I can't load or save settings in checkout-app (in dashboard).

<img width="1281" alt="" src="https://user-images.githubusercontent.com/70897052/177545254-d18acc40-8d81-4863-9ce1-5b2f7f1dbcdb.png">

The error message like this is quite useless. I have tried to reinstall the app, generate fresh authToken, redeploy both of vercel apps, to no avail.

What is actually wrong, and what can I do to fix it? What is unauthenticated?

Thank you!

EDIT:
I can see multiple requests in browser console:
```
GET https://saleor-checkout-app.vercel.app/api/payment-provider-settings
HTTP/401 Unauthenticated
{"error":{"message":"Unauthenticated"}}

POST https://saleor-checkout-app.vercel.app/api/set-payment-provider-settings
HTTP/401 Unauthenticated
{"error":{"message":"Unauthenticated"}}
```

**Comment by jamesknelson** [comment]
For anybody else struggling with this, I managed to get this working by removing the issuer check, and replacing all the usages of the issuer (which is a domain name) with the domain extracted from the existing NEXT_PUBLIC_SALEOR_API_URL env var. This should be safe so long as the jwksUri is also directed at the domain that your api is hosted on.

The files which need changing are all in saleor-app-checkout:

- auth.ts
- payment-provider-settings.ts
- set-payment-provider-settings.ts

For what it's worth, while having the issuer on the token would be ideal, it'd probably make more sense for `payment-provider-settings.ts` and `set-payment-provider-settings.ts` to use the apiUrl env var instead of reconstructing it from the token issuer in any case.

**Comment by mmiszy** [comment]
It's a Saleor Core bug. It'll be fixed in the core.

Internal link for reference: https://app.clickup.com/t/2549495/SALEOR-7262

**Comment by jTiKey** [comment]
Any updates, ETA when this will get fixed?

**Comment by mmiszy** [comment]
Closed via:
https://github.com/saleor/saleor/pull/10845
https://github.com/saleor/react-storefront/commit/4a93b7e4bc33f9d2a4f5ccd4e4c54b18560a910d
