### ISSUE TITLE
pnpm dev not run

### ISSUE THREAD

**Issue by dxrvip** [saleor/react-storefront#510]
### Summary

Hello everyone! My operation process: 
1. saleor storefront create
2.cd saleor-demo
3. pnpm i
4. pnpm dev
5. Thank you very much for your answer

### Steps to reproduce

C:\Users\Administrator\code\saleor\saleor-demo>pnpm dev

> saleor-demo@0.0.0 dev C:\Users\Administrator\code\saleor\saleor-demo
> env-cmd --no-override -f .env env-cmd --no-override -f .env.local --fallback pnpm run _dev

> saleor-demo@0.0.0 _dev C:\Users\Administrator\code\saleor\saleor-demo
> turbo run build --filter=@saleor/checkout-storefront --cache-dir=.turbo && turbo run dev --parallel --cache-dir=.turbo

 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at C:\Users\Administrator\AppData\Local\Temp\turbod\7ceedaebc12761a7\turbod.pid is not running, and remove C:\Users\Administrator\AppData\Local\Temp\turbod\7ceedaebc12761a7\turbod.pid
        - check the logs at C:\Users\Administrator\AppData\Local\turborepo\logs\7ceedaebc12761a7-saleor-demo.log
        - the unix domain socket at C:\Users\Administrator\AppData\Local\Temp\turbod\7ceedaebc12761a7\turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
• Packages in scope: @saleor/checkout-storefront
• Running build in 1 packages
@saleor/ui-kit:build: cache miss, executing 7ba5720391a5d1d6
checkout-common:build: cache miss, executing 3a20dae411fcd75b
checkout-common:build:
checkout-common:build: > checkout-common@0.1.0 build C:\Users\Administrator\code\saleor\saleor-demo\packages\checkout-common
checkout-common:build: > NODE_ENV=production rollup -c
checkout-common:build:
@saleor/ui-kit:build:
@saleor/ui-kit:build: > @saleor/ui-kit@0.0.0 build C:\Users\Administrator\code\saleor\saleor-demo\packages\ui-kit
@saleor/ui-kit:build: > rollup -c
@saleor/ui-kit:build:
checkout-common:build: 'NODE_ENV' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
checkout-common:build: ���������ļ���
checkout-common:build:  ELIFECYCLE  Command failed with exit code 1.
checkout-common:build: ERROR: command finished with error: command (C:\Users\Administrator\code\saleor\saleor-demo\packages\checkout-common) pnpm run build exited (1)
@saleor/ui-kit:build:
@saleor/ui-kit:build: src/index.ts → dist/cjs/index.js, dist/esm/index.js...
@saleor/ui-kit:build: created dist/cjs/index.js, dist/esm/index.js in 14s
@saleor/ui-kit:build:
@saleor/ui-kit:build: ./dist/esm/index.d.ts → dist/index.d.ts...
@saleor/ui-kit:build: (!) Unresolved dependencies
@saleor/ui-kit:build: https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@saleor/ui-kit:build: @lib/globalTypes (imported by dist/esm/components/Checkbox/Checkbox.d.ts, dist/esm/components/Chip/Chip.d.ts, dist/esm/components/IconButton/IconButton.d.ts, dist/esm/components/InfoTip/InfoTip.d.ts, dist/esm/components/Radio/Radio.d.ts, dist/esm/components/Select/Select.d.ts, dist/esm/components/Switch/Switch.d.ts, dist/esm/components/TextInput/TextInput.d.ts)
@saleor/ui-kit:build: created dist/index.d.ts in 453ms
command (C:\Users\Administrator\code\saleor\saleor-demo\packages\checkout-common) pnpm run build exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    55.643s

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

### Output from envinfo

C:\Users\Administrator\code\saleor\saleor-demo>npx envinfo --system --binaries --browsers --markdown
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

## System:
 - OS: Windows 10 10.0.19044
 - CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
 - Memory: 11.73 GB / 15.90 GB
## Binaries:
 - Node: 18.10.0 - C:\nodejs\node.EXE
 - npm: 8.19.2 - C:\nodejs\npm.CMD
## Browsers:
 - Internet Explorer: 11.0.19041.1566
--------------
C:\Users\Administrator\code\saleor\saleor-demo>pnpm --version
7.12.2

**Comment by dxrvip** [comment]
@peelar

**Comment by mmiszy** [comment]
Do you know what these mean?

```
checkout-common:build: 'NODE_ENV' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
checkout-common:build: ���������ļ���
```

These must be in unicode but they weren't printed correctly for some reason.

**Comment by akbari4yaseen** [comment]
Another issue: 

pnpm dev

> saleor-storefront@0.0.0 dev C:\Users\Akbari\Desktop\OC\react-storefront-canary\react-storefront-canary
> env-cmd --no-override -f .env env-cmd --no-override -f .env.local --fallback pnpm run _dev


> saleor-storefront@0.0.0 _dev C:\Users\Akbari\Desktop\OC\react-storefront-canary\react-storefront-canary
> turbo run build --filter=@saleor/checkout-storefront --cache-dir=.turbo && turbo run dev --parallel --cache-dir=.turbo --filter=!checkout

 WARNING  cannot find a .git folder. Falling back to manual file hashing (which may be slower). If you are running this build in a pruned directory, you can ignore this message. Otherwise, please initialize a git repository in the root of your monorepo
• Packages in scope: @saleor/checkout-storefront
• Running build in 1 packages
• Remote caching disabled
checkout-common:build: Failed to check if we can skip restoring outputs for checkout-common#build: rpc error: code = Unknown desc = timed out waiting for cookie. 
Proceeding to check cache
@saleor/ui-kit:build: Failed to check if we can skip restoring outputs for @saleor/ui-kit#build: rpc error: code = Unknown desc = timed out waiting for cookie. Proceeding to check cache
checkout-common:build: cache miss, executing 07fe997961d55702
@saleor/ui-kit:build: cache miss, executing e2d03e1b94e40965
@saleor/ui-kit:build: 
@saleor/ui-kit:build: > @saleor/ui-kit@0.0.0 build C:\Users\Akbari\Desktop\OC\react-storefront-canary\react-storefront-canary\packages\ui-kit
checkout-common:build:
checkout-common:build: > checkout-common@0.1.0 build C:\Users\Akbari\Desktop\OC\react-storefront-canary\react-storefront-canary\packages\checkout-commony\packages\checkout-common
checkout-common:build: > NODE_OPTIONS=--experimental-json-modules NODE_ENV=production rollup -c
checkout-common:build:
@saleor/ui-kit:build: 'NODE_OPTIONS' is not recognized as an internal or external command,
@saleor/ui-kit:build: operable program or batch file.
@saleor/ui-kit:build:  ELIFECYCLE  Command failed with exit code 1.
checkout-common:build: 'NODE_OPTIONS' is not recognized as an internal or external command,
checkout-common:build: operable program or batch file.
checkout-common:build:  ELIFECYCLE  Command failed with exit code 1.                                                          orefront-canary\packages\ui-kit) pnp
@saleor/ui-kit:build: ERROR: command finished with error: command (C:\Users\Akbari\Desktop\OC\react-storefront-canary\react-storefront-canary\packages\ui-kit) pnpm run build exited (1)
command (C:\Users\Akbari\Desktop\OC\react-storefront-canary\react-storefront-canary\packages\ui-kit) pnpm run build exited (1)


 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    2.216s

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
