### ISSUE TITLE
Improve Storefront x Checkout communication, by using Apps metadata

### ISSUE THREAD

**Issue by lkostrowski** [saleor/react-storefront#543]
## Context

- Checkout is an app
- Storefront is *not* an app
- ~Checkout needs env variable available during build, to "set" Storefront url~
- Storefront needs env variable during build, to "set" checkout URL

### Mutli-tenancy of checkout - need to handle many storefronts

Checkout, as a multi-tenant app, should work for many Saleors. That means there are many Storefronts, under differets URLs, that will redirect to checkout and checkout must redirect back.

If Storefront URL is hardcoded in envs, this solution will not work

### Deployment of storefront and checkout with "single app experience"

Besides both apps are separate, for users they are meant to work like one app. Toolkit around it (Marketplace, CLI) need to deploy both of them and they should work. 

This is very hard, and requires workaround, to achieve - URL of each of them is known after deployment, so there are redeployments needed to set this correctly. It requires additional services and "dirty work" in infrastructure. OOTB solution can't be achieved easily

### Can't configure storefront

Storefront is likely to be configured by shop owners. It's logic dedicated to each storefront implementation and default Saleor storefront doesn't have to have any specific settings inside Dashboard App. However this is likely to be requested.

### Dashboard is not aware of Storefront

Dashboard can't be extended with Storefront features, because it doesn't know it exists

## Solution description

Soluton discussed with @timuric & @patrys is to:

1. Make storefront an app - POC is already there https://github.com/saleor/react-storefront/pull/503
2. Create some basic Dashboard screen for Storefront, with checkout URL setting, saved to Private Metadata
3. Create extra checkout Dashboard Screen for Storefront URL and save to Pirvate Metadata
4. Set Multi-tenant checkout as a fallback/default value for storefront
5. Consume metadata in checkout & storefront and fetch Checkout/Storefront URL instead using envs
6. Create some fallback screen/info/error component in checkout, that Storefront is not configured (or handle it somehow else)

### Can extend Dashboard with Storefront extensions

Extensions can be used in Dashboard, eg "open product in shop"

### Webhooks can trigger builds

Webhooks can incrementally trigger rebuild on SSG/ISR

### Easy deployment & infra

Infrastructure will be much easier and simpler, and stable. Users can dynamically update values to test between different solutions.

Marketplace will be unblocked, because both apps can be deployed in any order, post-deploy can redirect to configuration screen

**Comment by witoszekdev** [comment]
> Create extra checkout Dashboard Screen for Storefront URL and save to Pirvate Metadata

If app is installed through marketplace we know it's URL - maybe we could make it even easier for users to set-up this app:
- Storefront stores it's URL in metadata after it's deployed (I assume storefront is single-tenant app)
- Checkout app queries all available apps to search for storefront app
Something like this:
```graphql
query {
  apps(filter: {type: THIRDPARTY, isActive: true, search: "Storefront"}) {
    edges {
      node {
        metafield(key: "storefrontUrl")
      }
    }
  }
}
```
- We autopopulate the storefront URL in config or give a select if there's more than 1 storefront

> Consume metadata in checkout & storefront and fetch Checkout/Storefront URL instead using envs

This will definitely require some caching (I can't imagine making a request to Saleor each time we want to redirect users / make another request to `saleor-app-checkout`). Maybe we should utilize Next.js cache + [on-demand cache invalidation](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#using-on-demand-revalidation) when  app is updated / storefront is re-deployed by using webhooks.

**Question: Do we even need checkout config for storefront?**
In general, we use `STOREFRONT_URL` only to build `saleor-app-checkout` API URL, that we then use to make requests - the reasoning here is that Storefront uses Next.js redirects that points to deployed checkout. IMHO, we could drop this entirely since we're using redirects and just use relative URL.

For example:
- Storefront URL: `https://my-storefront.saleor.io`
- Checkout deployment URL: `https://checkout.vercel.app`
- Storefront -> Checkout redirect URL: `https://my-storefront.saleor.io/saleor-app-checkout/`
- Storefront -> Checkout redirect URL for API: `https://my-storefront.saleor.io/saleor-app-checkout/api` (we just add `/api`)

**Comment by lkostrowski** [comment]
> If app is installed through marketplace we know it's URL - maybe we could make it even easier for users to set-up this app:
> 
> * Storefront stores it's URL in metadata after it's deployed (I assume storefront is single-tenant app)
> * Checkout app queries all available apps to search for storefront app
>   Something like this:

I think its "too smart" solution. Storefront & checkout should work together, but its likely that MT checkout will be used with custom storefront, not react-storefront.

It's checkout that needs this URL, so I don't think we should require *another* app to do something extra, so checkout can work. Checkout should enable its configuration explicitly (config screen). Looking "under the hood" for metadata is far from obvious and it couples apps.

We may use this as an "extra" to e.g. set default value for config, but I insist that checkout can be configured explicitly

**Comment by mmiszy** [comment]
> Checkout needs env variable available during build, to "set" Storefront url
I don't think it's true. Checkout doesn't need to know the storefront url.

**Comment by lkostrowski** [comment]
Suggestion after talking to @mmiszy:

1. Checkout can safely drop storefront URL env, because now its not used
2. Storefront will be an app and will have checkout URL config in metadata. Will drop env.
3. One day, when checkout needs storefront URL, will be added (after some refinement)

@mmiszy please confirm

**Comment by mmiszy** [comment]
I confirm 😎

**Comment by lkostrowski** [comment]
Same as #592 we are not ready yet to proceed with this due to authentication issues. We can revisit this topic when we solve auth problem
