### ISSUE TITLE
Adyen: We always send amount multiplied by 100 but we should not

### ISSUE THREAD

**Issue by mmiszy** [saleor/react-storefront#549]
In most cases, a minor unit of a currency is major * 100. I.e. 1USD = 100 cents, 1PLN = 100gr etc.
However, in some cases, that's not true. See the following table: https://docs.adyen.com/development-resources/currency-codes

- [ ] research if Adyen provides a function for this kind of conversion. It exists for iOS SDK (`AmountFormatter`), not sure about JS.
- [ ] use it instead of multiplying by 100

**Comment by witoszekdev** [comment]
We should do similar check for other payment providers, because Adyen currency precision could differ from standard [ISO 4217](https://pl.wikipedia.org/wiki/ISO_4217)

also we need to take into account Saleor's precision - currently it's not possible in our API to check the `Decimal` scalar precision
