### ISSUE TITLE
Is this storefront production ready? How may I deploy it for production?

### ISSUE THREAD

**Issue by ianthesecond** [saleor/react-storefront#72]
Hello, I'm new with Next.js and React and I've been meaning to try Saleor out for a while now but I would like to have a storefront with good foundations to have something to work on rather than making it entirely from scratch. How may host the storefront?

**Comment by zaiste** [comment]
Our storefront is a Next.js application. You can quickly deploy it on Vercel or you can self-host it.

Both Next.js and Saleor are production-grade solutions. The goal this project is to provide a solid foundation for building production e-commerce solutions with React.js. At the moment we only provide a limited set of features. We want to this project to be easily customisable so that you can quickly adapt it to your specific needs.
